spring.application.name=Z_GCP

# Cloud SQL \uC5F0\uACB0
spring.datasource.url=jdbc:mysql://google/${DB_NAME}?socketFactory=com.google.cloud.sql.mysql.SocketFactory&cloudSqlInstance=${CLOUD_SQL_INSTANCE}&useSSL=false
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA \uC124\uC815
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.default_schema=${DB_NAME}
spring.jpa.show-sql=true

# Google Cloud Storage \uC124\uC815 (Java SDK \uBC29\uC2DD)
gcp.storage.bucket=${GCP_BUCKET}